"""schema v1: wellness, sleep, activities, intraday, journal, scores

Revision ID: c574474bb88a
Revises: 
Create Date: 2026-08-10 16:25:32.783477
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



revision: str = 'c574474bb88a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payloads_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_key'), ['key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_name', sa.String(length=200), nullable=True),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('start_time_gmt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.String(length=40), nullable=True),
    sa.Column('timezone_id', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('elapsed_duration', sa.Float(), nullable=True),
    sa.Column('moving_duration', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('hr_time_in_zone_1', sa.Float(), nullable=True),
    sa.Column('hr_time_in_zone_2', sa.Float(), nullable=True),
    sa.Column('hr_time_in_zone_3', sa.Float(), nullable=True),
    sa.Column('hr_time_in_zone_4', sa.Float(), nullable=True),
    sa.Column('hr_time_in_zone_5', sa.Float(), nullable=True),
    sa.Column('aerobic_training_effect', sa.Float(), nullable=True),
    sa.Column('anaerobic_training_effect', sa.Float(), nullable=True),
    sa.Column('difference_body_battery', sa.Integer(), nullable=True),
    sa.Column('fit_file_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_id', name='uq_activity_user_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_start_time_gmt'), ['start_time_gmt'], unique=False)

    op.create_table('computed_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('recovery_band', sa.String(length=16), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('raw_load_trimp', sa.Float(), nullable=True),
    sa.Column('raw_load_edwards', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_scores_user_date')
    )
    with op.batch_alter_table('computed_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_computed_scores_score_date'), ['score_date'], unique=False)

    op.create_table('daily_wellness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('last_7d_avg_rhr', sa.Float(), nullable=True),
    sa.Column('min_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('avg_stress', sa.Float(), nullable=True),
    sa.Column('max_stress', sa.Integer(), nullable=True),
    sa.Column('stress_duration', sa.JSON(), nullable=True),
    sa.Column('stress_qualifier', sa.String(length=32), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('lowest_spo2', sa.Float(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.Column('bb_charged', sa.Integer(), nullable=True),
    sa.Column('bb_drained', sa.Integer(), nullable=True),
    sa.Column('bb_highest', sa.Integer(), nullable=True),
    sa.Column('bb_lowest', sa.Integer(), nullable=True),
    sa.Column('bb_most_recent', sa.Integer(), nullable=True),
    sa.Column('bb_at_wake', sa.Integer(), nullable=True),
    sa.Column('moderate_intensity_minutes', sa.Integer(), nullable=True),
    sa.Column('vigorous_intensity_minutes', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'calendar_date', name='uq_wellness_user_date')
    )
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_wellness_calendar_date'), ['calendar_date'], unique=False)

    op.create_table('intraday_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ts_gmt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'ts_gmt', name='uq_intraday_user_kind_ts')
    )
    with op.batch_alter_table('intraday_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intraday_series_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_intraday_series_ts_gmt'), ['ts_gmt'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_journal_user_date')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)

    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('sleep_start_gmt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_end_gmt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sleep_start_local', sa.String(length=40), nullable=True),
    sa.Column('sleep_end_local', sa.String(length=40), nullable=True),
    sa.Column('sleep_seconds', sa.BigInteger(), nullable=True),
    sa.Column('deep_seconds', sa.BigInteger(), nullable=True),
    sa.Column('light_seconds', sa.BigInteger(), nullable=True),
    sa.Column('rem_seconds', sa.BigInteger(), nullable=True),
    sa.Column('awake_seconds', sa.BigInteger(), nullable=True),
    sa.Column('unmeasurable_seconds', sa.BigInteger(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_qualifier', sa.String(length=32), nullable=True),
    sa.Column('awake_count', sa.Integer(), nullable=True),
    sa.Column('avg_sleep_stress', sa.Float(), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('lowest_spo2', sa.Float(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('body_battery_change', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sleep_start_gmt', name='uq_sleep_user_start')
    )
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_sessions_calendar_date'), ['calendar_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_sessions_sleep_start_gmt'), ['sleep_start_gmt'], unique=False)

    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=64), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stream', name='uq_sync_user_stream')
    )
    op.create_table('activity_hr_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_pk', sa.Integer(), nullable=False),
    sa.Column('elapsed_s', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_pk'], ['activities.id'], name='fk_hr_series_activity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_pk', 'elapsed_s', name='uq_hr_series_activity_elapsed')
    )
    with op.batch_alter_table('activity_hr_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_hr_series_activity_pk'), ['activity_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_hr_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_hr_series_activity_pk'))

    op.drop_table('activity_hr_series')
    op.drop_table('sync_state')
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_sleep_start_gmt'))
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_calendar_date'))

    op.drop_table('sleep_sessions')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('intraday_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intraday_series_ts_gmt'))
        batch_op.drop_index(batch_op.f('ix_intraday_series_kind'))

    op.drop_table('intraday_series')
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_wellness_calendar_date'))

    op.drop_table('daily_wellness')
    with op.batch_alter_table('computed_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_computed_scores_score_date'))

    op.drop_table('computed_scores')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_start_time_gmt'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_type'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_id'))

    op.drop_table('activities')
    op.drop_table('users')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_payloads_key'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_endpoint'))

    op.drop_table('raw_payloads')
    # ### end Alembic commands ###
