"""device_metrics table (VO2max snapshots)

Revision ID: ee3b7bb8893d
Revises: c574474bb88a
Create Date: 2026-08-10 17:40:37.811277
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



revision: str = 'ee3b7bb8893d'
down_revision: Union[str, None] = 'c574474bb88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('vo2max_precise', sa.Float(), nullable=True),
    sa.Column('fitness_age', sa.Integer(), nullable=True),
    sa.Column('max_met_category', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_date', name='uq_metrics_user_date')
    )
    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_metrics_metric_date'), ['metric_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_metrics_metric_date'))

    op.drop_table('device_metrics')
    # ### end Alembic commands ###
